/* Ficha local: nenhum dado é transmitido ou buscado em servidor. */
(() => {
  'use strict';
  const spec=JSON.parse(document.getElementById('missionSpec').textContent);
  const fields=['student','classroom','project','activityDate','deliveryVersion','commit','environment','changes','flow','validation','challenge','ai','conclusion'];
  const allowedStatus=['not-run','pass','fail','blocked'];
  const statusName={'not-run':'Não executado',pass:'Passou',fail:'Falhou',blocked:'Impedido pelo ambiente'};
  const named=n=>document.querySelector('[name="'+n+'"]');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let dirty=false, preparingPrint=false;
  function read(){const d={schema:'ifma.web.missao04.evidencias',schemaVersion:1,missionVersion:spec.version,documentId:'WEB-E3-I1-M04',exportedAt:new Date().toISOString(),answers:{},tests:{},declaration:named('declaration').checked};for(const k of fields)d.answers[k]=named(k).value;for(const [id] of spec.tests)d.tests[id]={status:named(id+'-status').value,observed:named(id+'-observed').value};return d;}
  function notify(text){document.getElementById('status').textContent=text;}
  function progress(){const d=read();const done=Object.values(d.tests).filter(t=>t.status!=='not-run').length;const pass=Object.values(d.tests).filter(t=>t.status==='pass').length;document.getElementById('testProgress').textContent=`${done} de ${spec.tests.length} cenários com resultado declarado; ${pass} marcados como Passou. Registro do estudante, não correção automática.`;}
  function filename(ext){const safe=(named('student').value||'estudante').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,60)||'estudante';return `web_missao_04_${safe}_v${(named('deliveryVersion').value||'1.0').replace(/[^a-zA-Z0-9._-]/g,'_')}.${ext}`;}
  function download(text,mime,ext){const blob=new Blob([text],{type:mime});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename(ext);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function markdown(d){const a=d.answers;let s=`# Ficha de evidências — Missão 04\n\n${spec.institution} — ${spec.campus}\n\n${spec.subject}\n\n${spec.teacher}\n\n**Documento:** WEB-E3-I1-M04 · versão da missão ${spec.version}\n\n**Exportação:** ${d.exportedAt}\n\n## Identificação\n\n`;for(const [label,k] of [['Estudante','student'],['Turma','classroom'],['Projeto analisado','project'],['Data realizada','activityDate'],['Versão da entrega','deliveryVersion'],['Commit','commit']])s+=`**${label}:** ${a[k]||'[não informado]'}\n\n`;for(const [label,k] of [['Ambiente e execução','environment'],['Alterações e preservação','changes'],['Fluxo dos dados','flow'],['Validação','validation']])s+=`## ${label}\n\n${a[k]||'[não informado]'}\n\n`;s+='## Testes declarados pelo estudante\n\n';for(const [id,input,expected] of spec.tests){const t=d.tests[id];s+=`### ${id} — ${statusName[t.status]}\n\n**Ação/entrada:** ${input}\n\n**Esperado:** ${expected}\n\n**Observado/evidência:** ${t.observed||'[não informado]'}\n\n`;}for(const [label,k] of [['Microdesafio individual','challenge'],['Uso de IA','ai'],['Conclusão e pendências','conclusion']])s+=`## ${label}\n\n${a[k]||'[não informado]'}\n\n`;return s+`**Declaração de revisão:** ${d.declaration?'confirmada pelo estudante':'não confirmada'}.\n\nEsta ficha é autodeclarada. Não é nota nem validação automática do código.\n`;}
  function validateDraft(d){if(!d||typeof d!=='object'||d.schema!=='ifma.web.missao04.evidencias'||d.schemaVersion!==1)throw Error('Arquivo não é um rascunho compatível da Missão 04.');if(!d.answers||typeof d.answers!=='object'||!d.tests||typeof d.tests!=='object')throw Error('Rascunho sem campos obrigatórios.');const clean={answers:{},tests:{},declaration:d.declaration===true};for(const k of fields){if(typeof d.answers[k]!=='string'||d.answers[k].length>20000)throw Error('Campo inválido: '+k);clean.answers[k]=d.answers[k];}for(const [id] of spec.tests){const t=d.tests[id];if(!t||!allowedStatus.includes(t.status)||typeof t.observed!=='string'||t.observed.length>20000)throw Error('Teste inválido: '+id);clean.tests[id]={status:t.status,observed:t.observed};}return clean;}
  function apply(d){for(const k of fields)named(k).value=d.answers[k];for(const [id] of spec.tests){named(id+'-status').value=d.tests[id].status;named(id+'-observed').value=d.tests[id].observed;}named('declaration').checked=d.declaration;progress();}
  function printDoc(d){const a=d.answers;const val=k=>esc(a[k]||'Não informado.');const para=(title,k)=>`<h2>${title}</h2><p>${val(k)}</p>`;let out=`<section class="coverpage"><div><p style="text-align:center;font-size:12pt;font-weight:bold">INSTITUTO FEDERAL DO MARANHÃO<br>CAMPUS ITAPECURU-MIRIM</p><p style="text-align:center">${esc(spec.course)}<br>${esc(spec.subject)}</p></div><div class="coverbody"><p class="muted">ATIVIDADE PRÁTICA INDIVIDUAL · E3-I1</p><h1>Formulários e validação<br>Ficha de evidências — Missão 04</h1><p><strong>Estudante:</strong> ${val('student')}</p><p><strong>Turma:</strong> ${val('classroom')}</p><p><strong>Projeto analisado:</strong> ${val('project')}</p><p><strong>Docente:</strong> ${esc(spec.teacher)}</p><p><strong>Data realizada:</strong> ${val('activityDate')}</p></div><div class="doc-control"><p><strong>Controle documental:</strong> WEB-E3-I1-M04<br>Versão da missão: ${spec.version} | Versão da entrega: ${val('deliveryVersion')}<br>Exportação: ${esc(d.exportedAt)}<br>Natureza: registro individual de evidências, autodeclarado.</p><p>Período letivo: 2026.2 · Itapecuru-Mirim — MA</p></div></section>`;
    out+='<h2>1. Identificação técnica da entrega</h2><div class="print-box"><p><strong>Commit individual:</strong> '+val('commit')+'</p></div>';
    out+=para('2. Ambiente e rota de execução','environment')+para('3. Alterações e preservação do projeto','changes')+para('4. Fluxo dos dados','flow')+para('5. Regras e bloqueio de entradas inválidas','validation');
    out+='<h2>6. Resultados dos testes</h2><p class="muted">As situações e resultados esperados vêm da especificação da missão. Os observados e as evidências abaixo foram declarados pelo estudante; não equivalem a uma nota automática.</p>';
    for(const [id,input,expected] of spec.tests){const t=d.tests[id];out+=`<section class="evidence-test"><h3>${id} — ${esc(statusName[t.status])}</h3><p><strong>Ação/entrada:</strong> ${esc(input)}</p><p><strong>Resultado esperado:</strong> ${esc(expected)}</p><p><strong>Resultado observado e evidência:</strong> ${esc(t.observed||'Não informado.')}</p></section>`;}
    out+=para('7. Microdesafio individual','challenge')+para('8. Uso de IA generativa','ai')+para('9. Conclusão e pendências','conclusion');
    out+='<h2>10. Critérios de avaliação previstos</h2><table><thead><tr><th>Critério</th><th style="width:20%">Valor</th></tr></thead><tbody>'+spec.rubric.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.points.toLocaleString('pt-BR')} ponto(s)</td></tr>`).join('')+'</tbody></table><p>Valor total: 2,5 pontos. A avaliação cabe ao professor, incluindo organização, explicação individual e compreensão do código.</p>';
    out+=`<h2>11. Declaração</h2><p>${d.declaration?'O estudante confirmou que revisou os dados, distinguiu resultados executados de itens pendentes e identificou o commit do trabalho que consegue explicar.':'A declaração de revisão não foi confirmada na ficha.'}</p><p class="signature">${val('student')}<br>Identificação declarada pelo estudante. Este documento não contém assinatura digital.</p>`;
    document.getElementById('printDocument').innerHTML=out;
  }
  document.getElementById('jsonBtn').onclick=()=>{download(JSON.stringify(read(),null,2),'application/json;charset=utf-8','json');dirty=false;notify('Rascunho JSON salvo. Ele pode ser recuperado por Carregar JSON; não foi enviado ao professor.');};
  document.getElementById('mdBtn').onclick=()=>{download(markdown(read()),'text/markdown;charset=utf-8','md');notify('Markdown exportado. Salve também o JSON para continuar o preenchimento.');};
  document.getElementById('loadBtn').onclick=()=>document.getElementById('jsonFile').click();
  document.getElementById('jsonFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('O JSON excede o limite de 2 MB.');const d=validateDraft(JSON.parse(await file.text()));if(dirty&&!confirm('Carregar o JSON substituirá o preenchimento atual. Continuar?'))return;apply(d);dirty=false;notify('Rascunho recuperado localmente. Confira identificação e resultados antes de entregar.');}catch(err){notify('Não foi possível carregar: '+err.message);}finally{e.target.value='';}};
  document.getElementById('pdfBtn').onclick=()=>{const d=read();printDoc(d);preparingPrint=true;document.title=filename('pdf').slice(0,-4);notify('Ficha A4 preparada. Escolha Salvar como PDF no diálogo de impressão.');window.print();preparingPrint=false;};
  document.getElementById('clearBtn').onclick=()=>{if(!confirm('Limpar a ficha? Salve o JSON antes para não perder as respostas.'))return;for(const k of fields)named(k).value=k==='deliveryVersion'?'1.0':'';for(const [id] of spec.tests){named(id+'-status').value='not-run';named(id+'-observed').value='';}named('declaration').checked=false;dirty=false;progress();notify('Ficha limpa. Nenhum resultado foi marcado automaticamente.');};
  document.querySelectorAll('.screen input,.screen textarea,.screen select').forEach(el=>{if(el.type==='file')return;el.addEventListener('input',()=>{dirty=true;progress();});el.addEventListener('change',()=>{dirty=true;progress();});});
  document.querySelectorAll('pre[data-copy]').forEach(pre=>{const row=document.createElement('div');row.className='copyrow';const b=document.createElement('button');b.className='smallbtn';b.type='button';b.textContent='Copiar comandos';row.append(b);pre.after(row);b.onclick=async()=>{try{await navigator.clipboard.writeText(pre.textContent);b.textContent='Copiado';setTimeout(()=>b.textContent='Copiar comandos',1800);}catch{const range=document.createRange();range.selectNodeContents(pre);getSelection().removeAllRanges();getSelection().addRange(range);notify('Comandos selecionados. Use Ctrl+C.');}};});
  window.addEventListener('beforeunload',e=>{if(dirty&&!preparingPrint){e.preventDefault();e.returnValue='';}});
  window.addEventListener('beforeprint',()=>printDoc(read()));
  window.mission04Evidence={read,printDoc,markdown,validateDraft};progress();
})();
