"""Storyboard da Aula 04. Conteúdo e recortes executáveis, sem gabarito da missão."""
import html

def render(spec, ex):
    e = html.escape
    def code(text, title='Trecho do exemplo', highlight=(), tag='RECORTE'):
        lines=''.join(f'<div class="line {"focus" if i in highlight else ""}"><span class="ln">{i}</span><span class="src">{e(line) or " "}</span></div>' for i,line in enumerate(text.splitlines(),1))
        return f'<div class="codebox"><div class="codehead"><span>{e(title)}</span><b>{e(tag)}</b></div><div class="codebody">{lines}</div></div>'
    def rule(t):return f'<div class="rule">{t}</div>'
    def call(t):return f'<div class="callout">{t}</div>'
    def demo(mode='full', title='EXEMPLO DIDÁTICO · biblioteca'):
        return f'<div class="form-scene"><div class="scene-head">{title}</div><div class="demo" data-mode="{mode}"></div></div>'
    def col(*items):return '<div class="col">'+''.join(items)+'</div>'
    def panel(title,text,cl=''):return f'<article class="panel {cl}"><h2>{title}</h2>{text}</article>'
    def note(t):return f'<p class="note">{t}</p>'
    def nums(items):return ''.join(f'<div class="annotation"><span class="num">{i}</span><p>{t}</p></div>' for i,t in enumerate(items,1))
    def questions(answers=False):
        qs=[('O que <code>v-model</code> faz aqui?','Liga o campo ao estado: digitar muda o ref; mudar o ref atualiza o campo.'),('O que <code>.prevent</code> impede?','A ação padrão da submissão. Ele não valida e não impede a chamada da função.'),('Por que <code>return</code> vem antes de <code>emit</code>?','Se há erro, encerra a função. Assim, o pai não recebe uma entrada inválida.'),('O sucesso sobrevive a um recarregamento?','Não neste exemplo. O estado da sessão não é banco de dados nem armazenamento local.')]
        return ''.join(f'<article class="q"><h2>{i} · {q}</h2>'+ (f'<div class="answer">{a}</div>' if answers else f'<button type="button" data-answer="answer-{i}" aria-controls="answer-{i}" aria-expanded="false">Ver resposta</button><div style="clear:both"></div><div id="answer-{i}" class="answer" hidden>{a}</div>')+'</article>' for i,(q,a) in enumerate(qs,1))
    slides=[]
    def add(title,body,cls='split',notes='',footer='Exemplo da biblioteca ≠ atividade individual. Dados apenas nesta sessão.',refs=True,kicker='FORMULÁRIOS'):
        if cls.lstrip().startswith('<'):
            body, cls = body + cls, 'split'
        slides.append((title,body,cls,notes,footer,refs,kicker))
    add('Do clique ao formulário', '<div><h2>Formulários que<br><span>orientam o usuário.</span></h2><p class="lead">Na Aula 3, o app reagia ao clique.<br>Agora ele também recebe informações.</p><p class="caption">Aula 04 · 2026.2 · 2 horas-aula<br>IFMA Campus Itapecuru-Mirim</p></div>'+panel('O caminho de hoje','<p>Receber entradas</p><p>Validar antes de registrar</p><p>Explicar erro ou sucesso</p>'), 'cover', '0–2 min. Retome o botão de interesse da aula anterior. Explique que o formulário é um novo componente do mesmo projeto; a aula não adiciona servidor ou banco.',refs=False,kicker='CONTINUIDADE')
    add('O Projeto 2 continua',col(panel('Não começaremos outro aplicativo.', '<p>Mantenha cabeçalho, cartões, rodapé e suas personalizações.</p><p>Vamos acrescentar um componente para receber informações.</p>'),rule('O contador de sugestões será <strong>separado</strong> do contador de interesses.')),col(code('src/\n├── App.vue\n└── components/\n    ├── AppHeader.vue\n    ├── ProjectCard.vue\n    ├── SuggestionForm.vue  # novo\n    └── AppFooter.vue', 'Projeto do estudante'),call('Diagnóstico: os dois cartões da Aula 3 precisam continuar reagindo de forma independente.')),notes='2–5 min. Peça a um estudante que aponte pai, filho, props, ref e evento. O repositório do professor conserva a base da Aula 2; não copiar seu src/ sobre a solução da Aula 3. Repare uma pendência com acompanhamento, sem apagar personalizações.',refs=False)
    add('Experimente antes de ver o código',col(demo()),col(panel('Tente quebrar o formulário.', '<p>1. Registre os dois campos vazios.</p><p>2. Preencha só com espaços.</p><p>3. Corrija e registre um recado válido.</p><p>4. Use Limpar e confira o resumo.</p>'),call('O recado fica no <strong>estado do App</strong>. Não é enviado à biblioteca nem ao professor.')),notes='5–8 min. Peça previsões e execute os quatro casos. Exemplo válido: assunto Novos livros; mensagem Gostaria de mais livros de programação. O total muda somente após um envio válido. Não chame isso de cadastro persistido.',kicker='PREVER → TESTAR → EXPLICAR')
    add('Quem guarda cada informação?',col(panel('Formulário · componente filho','<p><strong>Campos:</strong> assunto e mensagem.</p><p><strong>Feedback:</strong> erros e sucesso.</p><p><strong>Responsabilidade:</strong> validar antes de comunicar.</p>'),rule('O filho comunica um <strong>objeto de dados</strong> pelo evento <code>recado</code>.')),col(panel('App · componente pai','<p><strong>Total:</strong> quantos recados válidos recebeu.</p><p><strong>Último:</strong> dados do último recado.</p><p><strong>Responsabilidade:</strong> atualizar o resumo.</p>','blue'),rule('Formulário → evento <code>recado</code> → função do App.')),notes='Nomeie a informação, a origem e o destino: objeto de recado, componente do formulário e App. Não é mensagem entre pessoas nem tráfego de rede.',kicker='RESPONSABILIDADES')
    add('Um formulário tem estrutura',col(code('<form @submit.prevent="enviar">\n  <label for="assunto">Assunto</label>\n  <input id="assunto" v-model="assunto" />\n  <label for="mensagem">Mensagem</label>\n  <textarea id="mensagem"\n    v-model="mensagem"></textarea>\n  <button type="submit">\n    Registrar recado\n  </button>\n</form>', 'RecadoForm.vue · estrutura', (2,3,7)),rule('Clicar no rótulo <strong>Assunto</strong> também deve focalizar seu campo.')),col(demo()),notes='8–10 min. Mostre o vínculo for/id. A demonstração já está completa; o código à esquerda é um recorte estrutural. Mensagens, estilos e a lógica estão no painel Código do exemplo. Não apresente o recorte como arquivo inteiro.')
    add('O campo precisa de memória',col(code('\n'.join(ex['setup'].splitlines()[:4]),'RecadoForm.vue · estado inicial',(1,2)),nums(['<code>ref(\'\')</code> começa com um texto vazio.','<code>assunto</code> não é o elemento HTML: é o estado.','O template liga esse estado ao campo.']),rule('No script, usamos <code>assunto.value</code>.<br>No template, usamos <code>assunto</code>.')),col(demo('input','Inspetor do estado · digite no campo')),notes='10–12 min. Relembre .value sem transformar a aula em revisão longa. O botão de preencher é ferramenta didática, não requisito da missão. O v-model que liga o campo é explicado a seguir.')
    add('v-model conecta digitação e estado',col(code('<input v-model="assunto" />\n\n// Mudança feita no script:\nassunto.value = \'Novos livros\'','Campo ↔ ref',(1,4)),panel('A ligação funciona nos dois sentidos.','<p>Ao digitar, o estado recebe o texto.</p><p>Ao mudar o estado, o campo mostra o novo texto.</p>'),call('Não basta escrever <code>value="assunto"</code>: isso é um texto literal.')),col(demo('input','Digite; depois use Preencher pelo estado')),notes='12–14 min. Compare a saída do inspetor com a entrada. A ideia central é ligação entre estado e interface. O motor executa Vue real, não uma animação pré-programada de caracteres.')
    add('Texto longo também é entrada',col(code('<label for="mensagem">Mensagem</label>\n<textarea id="mensagem"\n  v-model="mensagem">\n</textarea>', 'Texto multilinha', (3,)),rule('Use <code>v-model</code> no <code>textarea</code>.<br>Não coloque <code>{{ mensagem }}</code> dentro dele.'),panel('Teste o teclado.','<p>Digite uma linha, pressione Enter e continue.</p><p>Enter aqui deve inserir uma quebra de linha.</p>')),col(demo('textarea','Mensagem · texto em mais de uma linha')),notes='14–16 min. Verifique Enter e Tab ao vivo. Na apresentação, atalhos de navegação não podem capturar a digitação. Demonstre uma quebra real de linha.')
    add('Enviar é um evento do formulário',col(code('<form @submit.prevent="contarEnvio">\n  <input v-model="texto" />\n  <button type="submit">\n    Registrar recado\n  </button>\n</form>\n\nfunction contarEnvio() {\n  tentativas.value += 1\n}', 'Demonstração isolada do submit',(1,3,9)),rule('<code>.prevent</code> impede a ação padrão.<br><strong>Não valida o conteúdo.</strong>')),col(demo('submit','Teste clique e Enter no input')),notes='16–18 min. Aqui o código e a prévia contam tentativas e ainda não validam. Clique no botão; depois pressione Enter no input. O número deve subir uma vez em cada ação. Não ligue a mesma função em @click e @submit: isso causa duplicidade.')
    add('Espaços não formam uma resposta',col(code("const dados = {\n  assunto: assunto.value.trim(),\n  mensagem: mensagem.value.trim()\n}", 'Normalizar antes de validar',(2,3)),panel('trim() remove as extremidades.','<p><code>\'   \'.trim()</code> vira <code>\'\'</code>.</p><p>Os espaços entre palavras continuam no texto.</p>'),call('A regra usa o texto normalizado, não a quantidade de teclas pressionadas.')),col(demo('trim','Texto bruto → trim() → tamanho')),notes='18–20 min. Use os dois botões. Mostre que Novos  livros mantém os dois espaços internos. Não usar trim para alterar a entrada a cada tecla: o aluno deve poder digitar naturalmente.')
    add('Escreva a regra antes da função',col(panel('Exemplo · biblioteca','<p><strong>Assunto:</strong> obrigatório, 4 a 40 caracteres.</p><p><strong>Mensagem:</strong> obrigatória, 10 a 200 caracteres.</p><p>As faixas são inclusivas e avaliadas <strong>após trim()</strong>.</p>'),code('if (!n) erros[campo] = `Preencha ${campo}.`\nelse if (n < min || n > max)\n  erros[campo] = `Use de ${min} a ${max} caracteres.`','validar-recado.js · regra',(1,2)),call('Na missão, os limites serão outros.<br>Não copie os números do exemplo.')),col(demo('bounds','Clique nos valores de fronteira')),notes='20–22 min. Preveja 3, 4, 40 e 41. A mesma função validar do exemplo calcula a resposta. O for do código completo é uma forma de reaproveitar a regra: não exigir que o aluno use loop ou o mesmo estilo de implementação.')
    add('Erro útil explica como corrigir',col(code("const erros = ref({\n  assunto: '', mensagem: ''\n})\n\n// Ao editar um campo:\nfunction editar(campo) {\n  sucesso.value = ''\n  erros.value[campo] = ''\n}",'Estado das mensagens',(7,8)),rule('Mostre o <strong>campo</strong>, o <strong>problema</strong> e como <strong>corrigir</strong>.'),call('Entrada inválida: preserve o texto.<br>Editar um campo não apaga o outro.')),col(demo()),notes='22–24 min. Gere dois erros, corrija apenas o assunto e observe o erro da mensagem permanecer. A edição limpa o feedback antigo daquele campo; a validação completa ocorre na próxima submissão.')
    add('return impede o caminho errado',col(code('\n'.join(ex['setup'].splitlines()[15:21]),'RecadoForm.vue · início de enviar()', (5,6)),panel('Antes de comunicar ao App…','<p>Normalize e valide.</p><p>Guarde as mensagens de erro.</p><p>Havendo erro, <code>return</code> encerra a função.</p>'),rule('Tentativa inválida → <strong>zero novos recados</strong> no resumo.')),col(demo()),notes='24–25 min. O trecho é extraído da mesma função usada pela demonstração. Teste assunto curto com mensagem válida. O total não muda. Esse é o motivo de o return vir antes do emit.')
    add('Só dados válidos chegam ao pai',col(code("emit('recado', resultado.dados)\n\n// Exemplo do objeto comunicado:\n{\n  assunto: 'Novos livros',\n  mensagem: 'Mais livros de programação.'\n}",'De uma string para um objeto',(1,)),panel('O evento carrega dois textos.','<p><code>recado</code> é o nome do evento.</p><p><code>resultado.dados</code> é o objeto normalizado.</p>'),call('“Chegar ao pai” significa <strong>chamar o componente App</strong>, não enviar ao servidor.')),col(demo()),notes='25–26 min. Retome a Aula 3: o evento de interesse levava uma string. Agora temos assunto e mensagem no mesmo objeto. Pergunte quem produz, o que comunica e onde chega; resposta: formulário, objeto normalizado, App.')
    add('O App escuta e atualiza o resumo',col(code(ex['parentSetup'],'App.vue · estado do pai',(4,5)),code('<RecadoForm\n  @recado="registrarRecado"\n/>','App.vue · listener',(2,)),rule('Somente um recado <strong>válido</strong> aumenta o total. O App guarda os dados recebidos.')),col(demo()),notes='26–27 min. Registre dois recados diferentes. Verifique total 2 e último igual ao segundo. O resumo é independente dos erros do filho. Não confundir este total com total de interesses já existente.')
    add('Quando limpar? Quando preservar?',col(panel('Erro → preservar','<p>Mantenha campos preenchidos para corrigir.</p>'),panel('Sucesso → limpar campos','<p>Primeiro comunique os dados; depois limpe e confirme.</p>','blue'),panel('Limpar → não apagar o resumo','<p>O botão limpa o estado do formulário, não os dados recebidos pelo App.</p>','amber')),col(demo()),notes='27–28 min. Teste Limpar durante erro e depois de sucesso. O type=button impede que Limpar envie o formulário. Uma segunda tentativa vazia não pode repetir o registro anterior.')
    add('Usar teclado também precisa funcionar',col(code('<label for="assunto">Assunto</label>\n<input id="assunto"\n  v-model="assunto"\n  :aria-invalid="Boolean(erros.assunto)"\n  aria-describedby="erro-assunto" />\n<p id="erro-assunto" role="alert">\n  {{ erros.assunto }}\n</p>','Rótulo + erro associado',(1,4,5)),nums(['Tab percorre campos e botões.','Enter no input registra; no textarea, cria linha.','Foco e mensagens não dependem só de cor.'])),col(demo()),notes='28–29 min. Inspecione o foco usando Tab. O recorte omite a ajuda associada por brevidade, disponível no código completo. Testes automatizados fazem conferência básica do DOM; o professor ainda observa foco, contraste e clareza.')
    add('Não basta testar o caminho feliz',''.join(f'<article class="flowstep"><span class="num">{i}</span><h2>{t}</h2><p>{d}</p></article>' for i,(t,d) in enumerate([('Vazio','Dois erros; total não muda.'),('Só espaços','Mesma rejeição do vazio.'),('Limites','Teste abaixo, no limite e acima.'),('Válido','Um registro; dados normalizados.'),('Repetição','Clique após limpeza não duplica.'),('Recarregar','Zera o estado desta sessão.')],1)),'flowgrid',notes='29–30 min. Peça que alunos antecipem os observados. As faixas da atividade estão na ficha; não usar só screenshot do caminho feliz como evidência de validação.')
    add('Três bugs: preveja, execute, corrija','<div class="bugbox" data-mode="bugs"></div>','',notes='30–32 min. 1) Sem v-model: o DOM recebe digitação mas o estado fica vazio. 2) Sem trim: quatro espaços no assunto e dez na mensagem passam. 3) Emit antecipado: total muda antes da validação. Corrigir demonstração reseta o cenário com a correção aplicada; Reiniciar restaura o bug original.',kicker='DEPURAÇÃO')
    add('Explique o que aconteceu',questions(),'qgrid',notes='32–34 min. Dê tempo para o aluno responder antes de revelar. Todas as respostas estão no próprio slide e na síntese seguinte.',kicker='PERGUNTAS')
    add('Confira as respostas',questions(True),'qgrid',notes='34–35 min. Sintetize as quatro respostas sem introduzir API ou localStorage. Estado de sessão não é persistência.',kicker='SÍNTESE')
    add('Missão 04 · uma sugestão que o sistema entende',col(panel('Seu projeto, sua sugestão.','<p>Crie <code>SuggestionForm.vue</code>.</p><p>Receba título e descrição de uma melhoria para o contexto do seu projeto.</p><p>O App mostra total e última sugestão válida.</p>'),call('Atividade <strong>individual</strong>. Preserve a evolução da Aula 3.')),col(panel('Regras da missão','<p><strong>Título:</strong> 5–60 caracteres.</p><p><strong>Descrição:</strong> 15–300 caracteres.</p><p>Obrigatórios; contar após <code>trim()</code>.</p><p>Não registrar inválidos; preservar entradas para correção.</p>','blue'),rule('Evento da missão: <code>sugestao</code>.<br>Objeto: <code>{ titulo, descricao }</code>.')),notes='35–37 min. Aponte a diferença de nomes e limites entre biblioteca e sugestão. Abra a página da atividade pelo portal. Não distribuir o gabarito docente. Formulário de evidências do site não é o aplicativo do aluno.',refs=False,kicker='E3-I1 · INDIVIDUAL')
    add('Construa por checkpoints',''.join(f'<article class="flowstep"><span class="num">{i}</span><h2>{t}</h2><p>{d}</p></article>' for i,(t,d) in enumerate([('Proteger a base','Execute o app e registre o progresso.'),('Receber entradas','Dois campos associados ao estado.'),('Aplicar regras','Normalize e rejeite entradas inválidas.'),('Orientar','Erros por campo; sucesso verdadeiro.'),('Integrar','Evento válido → resumo do App.'),('Testar e entregar','Fronteiras, regressão e commit individual.')],1)),'flowgrid',notes='37–38 min. Esses blocos também estão na atividade. Durante os 50 minutos de laboratório, observe a explicação individual e proponha uma pequena alteração de regra.',refs=False,kicker='MISSÃO 04')
    add('Como serão avaliados os 2,5 pontos',''.join(f'<article class="q"><h2>{str(r["points"]).replace(".",",")} ponto{"s" if r["points"]!=1 else ""} · {e(r["name"])}</h2><p>{e(r["evidence"])}</p></article>' for r in spec['rubric']),'qgrid',notes='38–40 min. Rubrica do plano E3-I1 preservada. Checker não dá nota oficial e não mede sozinho autoria. A data de aplicação e o prazo serão comunicados pelo docente, sem reaproveitar automaticamente a previsão de agosto.',refs=False,kicker='RUBRICA')
    add('Como conferir e entregar',col(code('node course/runner.mjs status\nnode course/runner.mjs mission 04\nnode course/runner.mjs check 04','Depois da instalação inicial',(3,)),rule('Mantenha <code>npm run dev</code> em um terminal. Execute o checker em <strong>outro terminal</strong>.'),call('Sem ambiente de teste → <strong>NÃO VERIFICADO</strong>. Registre testes manuais; não invente aprovação.')),col(code('git status\ngit add .\ngit commit -m "feat: conclui missao 04"\ngit push origin main','Após revisar os arquivos da entrega',(1,4)),panel('Instalação e atualização','<p>A atividade tem o instalador inicial de <code>course/</code>.</p><p><code>update</code> não substitui <code>src/</code>. Confira os remotes no guia.</p>')),notes='90–95 min. Instalar o runner e preparar o Playwright é tarefa anterior do laboratório. O enunciado funciona sem eles. Confira os arquivos antes de git add para não incluir segredos, node_modules ou respostas alheias. Origin é do aluno. Não rodar pull upstream main.',refs=False,kicker='ENTREGA')
    add('Definição de pronto',col(panel('Funciona de verdade.','<p>Inválido orienta e não registra.</p><p>Válido registra uma vez e confirma.</p><p>Teclado, Limpar e cartões antigos continuam funcionando.</p>'),rule('Demonstre um caso <strong>abaixo</strong> e outro <strong>no limite</strong> de uma regra.')),col(panel('Há evidência individual.','<p>Componente próprio e commit identificável.</p><p>Testes com entradas, esperado e observado.</p><p>Uso de IA declarado e código explicável.</p>','blue'),call('“O build passou” não comprova tudo.<br><strong>O checker também tem limites.</strong>')),notes='95–100 min. Conferir commit e ficha. A ficha exportada não envia automaticamente a atividade. Prazo e canal de entrega são os comunicados pelo professor. Dificuldade de infraestrutura deve ser anotada separadamente.',refs=False,kicker='FECHAMENTO')
    refs=spec['references'][:5]
    add('Referências para consultar',''.join(f'<article class="reference"><h2>{e(t)}</h2><p>{e(d)}</p><a href="{e(u)}" target="_blank" rel="noopener noreferrer">Abrir documentação ↗</a></article>' for (t,u),d in zip(refs,['Campos ligados ao estado.','Submissão e modificadores de eventos.','Evento e dados recebidos no pai.','Erros claros e associados aos campos.','Limites da validação no cliente.']))+ '<article class="reference"><h2>Materiais da disciplina</h2><p>Plano Web v2, Aula 03 e guia origin/upstream.</p><a href="../docs/guia-origin-upstream/">Abrir guia do aluno ↗</a></article>','refgrid',notes='Referências técnicas conferidas para os mecanismos; sequência e rubrica vieram do plano da disciplina. A validação do cliente não substitui a futura validação de servidor.',refs=False,kicker='CONSULTA')
    add('Mapa do código do exemplo',col(panel('Recado para a biblioteca','<p><strong>RecadoForm.vue:</strong> campos, estado, mensagens e submissão.</p><p><strong>validar-recado.js:</strong> regras e normalização.</p><p><strong>App.vue:</strong> recebe o objeto e atualiza o resumo.</p>'),call('EXEMPLO DIDÁTICO.<br>Não é a solução de <code>SuggestionForm.vue</code>.')),col('<button class="actionbtn" data-open-code="RecadoForm.vue">Abrir RecadoForm.vue</button>','<button class="actionbtn secondary" data-open-code="validar-recado.js">Abrir validar-recado.js</button>','<button class="actionbtn secondary" data-open-code="App.vue · exemplo isolado">Abrir App do exemplo</button>',rule('Os corpos das funções usados nas demos são os mesmos apresentados no painel de código.'),note('O projeto real da turma continua com a versão fixada no seu <code>package-lock.json</code>.')),notes='Consulta após a explicação. O runtime da apresentação é Vue 3.5.13, reaproveitado da Aula 3; as macros dos SFCs são representadas por setup/emits equivalentes. Nenhuma versão de dependência do projeto foi alterada.',refs=False,kicker='CÓDIGO COMPLETO DO EXEMPLO')
    out=[]
    for i,(title,body,cls,notes,footer,refs,kicker) in enumerate(slides,1):
        cover=' cover' if cls=='cover' else ''
        content_cls='' if cls=='cover' else cls
        sources='<a href="https://vuejs.org/guide/essentials/forms.html">Vue · formulários</a> · <a href="https://vuejs.org/guide/essentials/event-handling.html">Vue · eventos</a> · <a href="https://www.w3.org/WAI/tutorials/forms/notifications/">W3C · feedback</a>' if refs else 'IFMA · Desenvolvimento de Sistemas Web · Aula 04'
        out.append(f'<section class="slide{cover}" id="s{i:02}" data-title="{e(title,quote=True)}" aria-labelledby="title{i:02}" role="group"><div class="meta"><span>AULA 04 · {kicker}</span><span class="brand">IFMA</span></div><h1 class="title" id="title{i:02}">{title}</h1><div class="content {content_cls}">{body}</div><div class="source">{sources}</div><footer class="footer"><span>{footer}</span><span class="n">{i:02} / {len(slides):02}</span></footer><template class="speaker-notes">{e(notes)}</template></section>')
    return '\n'.join(out), [{'slide':i,'title':v[0],'notes':v[3]} for i,v in enumerate(slides,1)]
