/** Checker comportamental da Missão 04. Resultados observáveis; sem nota ou gabarito. */
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';
import { protectedSnapshot } from '../lib/update.mjs';
const COURSE=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const spec=JSON.parse(fs.readFileSync(path.join(COURSE,'missions/04/mission.json'),'utf8'));
const assert=(condition,message)=>{if(!condition)throw Error(message);};
const nid='data-testid';

export async function loadBrowser(){
  const candidates=[];
  if(process.env.IFMA_PLAYWRIGHT_MODULE)candidates.push(pathToFileURL(path.resolve(process.env.IFMA_PLAYWRIGHT_MODULE)).href);
  const req=createRequire(path.join(COURSE,'package.json'));
  for(const name of ['playwright-core','playwright'])try{candidates.push(pathToFileURL(req.resolve(name)).href);}catch{}
  candidates.push(pathToFileURL(path.join(os.homedir(),'.ifma-web-tools/node_modules/playwright-core/index.mjs')).href);
  let pw;for(const c of candidates)try{pw=await import(c);break;}catch{}
  if(!pw?.chromium)throw Error('Playwright não preparado. Consulte docs/PREPARAR_VERIFICADOR.md com o professor.');
  const attempts=process.env.IFMA_BROWSER_PATH?[{executablePath:process.env.IFMA_BROWSER_PATH}]:[{channel:'msedge'},{channel:'chrome'},{executablePath:'/usr/bin/chromium'},{}];
  let err;for(const options of attempts)try{return await pw.chromium.launch({...options,headless:true});}catch(e){err=e;}
  throw Error('Nenhum navegador preparado pôde iniciar. Políticas do laboratório podem bloquear a automação. '+String(err?.message||'').slice(0,160));
}
export async function testUI(page,url,{loadDocument=null}={}){
  const results=[];const q=id=>page.locator(`[${nid}="${id}"]`);
  const text=async id=>{const el=q(id);return await el.count()?(await el.first().textContent()||'').trim():'';};
  const total=async()=>Number(await text('suggestion-total'));
  const visibleText=async id=>{const el=q(id);return await el.count()&&await el.first().isVisible()?(await el.first().textContent()||'').trim():'';};
  const zeroErrors=async()=>{assert(!(await visibleText('title-error')),'Erro de título permaneceu.');assert(!(await visibleText('description-error')),'Erro de descrição permaneceu.');};
  async function reset(){if(loadDocument)await loadDocument();else await page.goto(url,{waitUntil:'networkidle',timeout:15000});await q('suggestion-form').waitFor({state:'visible',timeout:4000});}
  async function fill(title,desc){await q('title-input').fill(title);await q('description-input').fill(desc);}
  async function send(){await q('submit-suggestion').click();await page.waitForTimeout(45);}
  async function valid(title='Melhorar acesso',desc='Instalar sinalização clara no corredor.'){await fill(title,desc);await send();}
  async function invalid(){assert(await total()===0,'Uma entrada inválida alterou o total.');assert(!(await visibleText('suggestion-success')),'Sucesso mostrado para entrada inválida.');}
  async function boundary(id,value){const el=q(id);await el.fill(value);if(await el.inputValue()!==value)await el.evaluate((node,v)=>{node.value=v;node.dispatchEvent(new Event('input',{bubbles:true}));},value);assert(await el.inputValue()===value,'A entrada de fronteira não chegou ao campo.');}
  const cases={
    T01:async()=>{await send();await invalid();assert(await visibleText('title-error'),'Falta mensagem para título vazio.');assert(await visibleText('description-error'),'Falta mensagem para descrição vazia.');},
    T02:async()=>{await fill('      ','                    ');await send();await invalid();assert(await visibleText('title-error')&&await visibleText('description-error'),'Espaços não foram tratados como vazio.');},
    T03:async()=>{for(const [n,ok] of [[4,false],[5,true],[60,true],[61,false]]){await reset();await fill('Titulo','Descrição válida para o teste.');await boundary('title-input','A'.repeat(n));await send();assert(await total()===(ok?1:0),'Título com '+n+' caracteres teve resultado incorreto.');assert(ok?!(await visibleText('title-error')):!!(await visibleText('title-error')),'Feedback de título incorreto para '+n+'.');}},
    T04:async()=>{for(const [n,ok] of [[14,false],[15,true],[300,true],[301,false]]){await reset();await fill('Titulo','Descrição válida para o teste.');await boundary('description-input','B'.repeat(n));await send();assert(await total()===(ok?1:0),'Descrição com '+n+' caracteres teve resultado incorreto.');assert(ok?!(await visibleText('description-error')):!!(await visibleText('description-error')),'Feedback de descrição incorreto para '+n+'.');}},
    T05:async()=>{await valid('  Mais  livros  ','  Desejo mais  livros para estudar.  ');assert(await total()===1,'Não registrou o caso válido.');assert(await q('suggestion-last-title').textContent()==='Mais  livros','Título não foi normalizado corretamente.');assert(await q('suggestion-last-description').textContent()==='Desejo mais  livros para estudar.','Descrição não preservou espaços internos/remover extremos.');},
    T06:async()=>{await fill('abc','Descrição válida para o teste.');await send();await invalid();assert(await visibleText('title-error'),'Não mostrou o erro de título.');assert(!(await visibleText('description-error')),'Mostrou erro indevido na descrição.');assert(await q('title-input').inputValue()==='abc'&&await q('description-input').inputValue()==='Descrição válida para o teste.','Apagou dados na submissão inválida.');await reset();await fill('Titulo','abc');await send();await invalid();assert(!(await visibleText('title-error'))&&await visibleText('description-error'),'Não isolou o erro da descrição.');},
    T07:async()=>{await send();await q('title-input').fill('Novos livros');assert(!(await visibleText('title-error')),'Erro antigo do campo editado permaneceu.');assert(await visibleText('description-error'),'Editar título apagou o erro do outro campo.');await q('description-input').fill('Comprar livros de programação.');await send();assert(await total()===1,'Correção não gerou exatamente um registro.');await zeroErrors();assert(await visibleText('suggestion-success'),'Sucesso não informado.');await q('title-input').fill('Outra sugestão');assert(!(await visibleText('suggestion-success')),'Sucesso antigo não desapareceu ao editar.');},
    T08:async()=>{await page.evaluate(()=>{window.__ifmaNavigationSentinel='same-document';});await valid();assert(await total()===1,'Clique não gerou exatamente um registro.');await fill('Outra sugestão','Mais espaços acessíveis para a turma.');await q('title-input').press('Enter');await page.waitForTimeout(50);assert(await total()===2,'Enter no input não gerou exatamente um segundo registro.');assert(await page.evaluate(()=>window.__ifmaNavigationSentinel)==='same-document','Formulário recarregou/navegou a página.');},
    T09:async()=>{await fill('Novo espaço','Linha inicial');await q('description-input').press('End');await q('description-input').press('Enter');assert((await q('description-input').inputValue()).includes('\n'),'Enter no textarea não criou linha.');assert(await total()===0,'Enter no textarea enviou indevidamente.');},
    T10:async()=>{await valid();const last=await text('suggestion-last-title');await fill('abc','');await send();await q('clear-suggestion').click();assert(await q('title-input').inputValue()===''&&await q('description-input').inputValue()==='','Limpar não apagou os campos.');await zeroErrors();assert(!(await visibleText('suggestion-success')),'Limpar não apagou o sucesso.');assert(await total()===1&&await text('suggestion-last-title')===last,'Limpar alterou o resumo no App.');},
    T11:async()=>{await valid();assert(await q('title-input').inputValue()===''&&await q('description-input').inputValue()==='','Sucesso não limpou os campos.');await send();assert(await total()===1,'Segunda tentativa vazia duplicou o registro.');assert(!(await visibleText('suggestion-success')),'Segunda tentativa inválida manteve sucesso.');},
    T12:async()=>{await valid('Mais árvores','Plantar árvores no pátio da escola.');await valid('Acesso seguro','Melhorar o acesso à biblioteca da escola.');assert(await total()===2,'Total após dois envios não é 2.');assert(await text('suggestion-last-title')==='Acesso seguro'&&await text('suggestion-last-description')==='Melhorar o acesso à biblioteca da escola.','Última sugestão não corresponde ao segundo envio.');},
    T13:async()=>{const b=page.locator('.project-card button');assert(await b.count()>=2,'São necessários os dois cartões interativos da Aula 3.');await b.nth(0).click();assert(await b.nth(0).isDisabled(),'Primeiro cartão não bloqueou repetição.');assert(await b.nth(1).isEnabled(),'Marcar um cartão também marcou o outro.');assert(Number(await text('interest-total'))===1,'Resumo de interesses não registrou o primeiro clique.');await valid();assert(Number(await text('interest-total'))===1,'Sugestão alterou indevidamente o total de interesses.');await b.nth(1).click();assert(await b.nth(1).isDisabled()&&Number(await text('interest-total'))===2,'Segundo cartão/resumo não preservado.');assert(await total()===1,'Interesse alterou indevidamente total de sugestões.');},
    T14:async()=>{await send();for(const [input,error] of [['title-input','title-error'],['description-input','description-error']]){const info=await q(input).evaluate(el=>({labels:el.labels?.length||0,invalid:el.getAttribute('aria-invalid'),described:el.getAttribute('aria-describedby')||'',id:el.id}));assert(info.labels>0,'Campo sem label associado: '+input);assert(info.invalid==='true','aria-invalid não anuncia erro: '+input);const errorId=await q(error).getAttribute('id');assert(errorId&&info.described.split(/\s+/).includes(errorId),'Erro não associado via aria-describedby: '+input);}await q('title-input').focus();await q('title-input').press('Tab');assert(await q('description-input').evaluate(el=>el===document.activeElement),'Tab não chega ao textarea.');await page.keyboard.press('Tab');assert(await q('submit-suggestion').evaluate(el=>el===document.activeElement),'Tab não chega a Registrar.');assert(await q('submit-suggestion').getAttribute('type')==='submit','Registrar não tem type=submit.');assert(await q('clear-suggestion').getAttribute('type')==='button','Limpar precisa de type=button.');},
    T15:async()=>{await valid();if(loadDocument)await loadDocument();else await page.reload({waitUntil:'networkidle'});assert(await total()===0,'Recarregar não reiniciou o estado da sessão.');assert(await q('title-input').inputValue()===''&&await q('description-input').inputValue()==='','Campos não reiniciaram.');}
  };
  for(const [id,input,expected] of spec.tests.filter(t=>t[0]!=='T16')){const jsErrors=[];const handler=e=>jsErrors.push(e.message);page.on('pageerror',handler);try{await reset();await cases[id]();assert(jsErrors.length===0,'Erro JavaScript: '+jsErrors.join('; '));results.push({id,input,expected,status:'PASS',observed:'Comportamento esperado observado no navegador.'});}catch(e){results.push({id,input,expected,status:'FAIL',observed:e.message});}finally{page.off('pageerror',handler);}}
  return results;
}
function buildCheck(project){const [id,input,expected]=spec.tests.find(t=>t[0]==='T16');const bin=path.join(project,'node_modules/vite/bin/vite.js');if(!fs.existsSync(bin))return {id,input,expected,status:'NOT_VERIFIED',observed:'Dependências do projeto não estão instaladas. Nenhum build foi executado.'};const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ifma-web-build-'));try{const res=spawnSync(process.execPath,[bin,'build','--outDir',dir,'--emptyOutDir'],{cwd:project,encoding:'utf8',timeout:60000,maxBuffer:1024*1024});const output=(res.stdout||'')+'\n'+(res.stderr||'');return {id,input,expected,status:res.status===0?'PASS':'FAIL',observed:res.error?.message||output.slice(-10000)};}finally{fs.rmSync(dir,{recursive:true,force:true});}}
function safeOutput(project){let dir=project;for(const part of ['docs','entregas','missao-04']){dir=path.join(dir,part);if(fs.existsSync(dir)&&fs.lstatSync(dir).isSymbolicLink())throw Error('Destino de evidências é link: '+dir);fs.mkdirSync(dir,{recursive:true});}return dir;}
export async function run(project,args=[]){
  let url='http://127.0.0.1:5173';for(let i=0;i<args.length;i++){if(args[i]==='--url'&&args[i+1])url=args[++i];else throw Error('Argumento inválido. Use check 04 --url http://127.0.0.1:5173');}
  const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol)||!['127.0.0.1','localhost','[::1]'].includes(parsed.hostname)||parsed.username||parsed.password)throw Error('O checker aceita somente a URL local do seu app.');
  const before=protectedSnapshot(project);const report={schema:'ifma.web.checker04',version:spec.version,at:new Date().toISOString(),url,environment:{node:process.version,platform:process.platform},scope:'Testes de comportamento observável. Comunicação ao pai é observada pelo resumo, não interceptada como tráfego de rede.',manualReview:['Separação de responsabilidades e integração do componente.','Nomes/estilos personalizados, clareza das mensagens e contexto.','Foco visível, contraste e compreensão individual.','Autoria e correspondência do commit entregue.'],tests:[]};
  let browser,context;
  try{browser=await loadBrowser();report.environment.browser=browser.version();context=await browser.newContext({viewport:{width:1280,height:850},locale:'pt-BR'});await context.route('**/*',route=>{const u=new URL(route.request().url());return ['127.0.0.1','localhost','[::1]'].includes(u.hostname)?route.continue():route.abort();});const page=await context.newPage();await page.goto(url,{waitUntil:'networkidle',timeout:10000});const needed=['suggestion-form','title-input','description-input','submit-suggestion','clear-suggestion','suggestion-total'];for(const x of needed)assert(await page.locator(`[${nid}="${x}"]`).count()===1,'Seletor obrigatório ausente ou duplicado: '+x);report.tests=await testUI(page,url);}catch(error){report.environment.blocker=error.message;for(const [id,input,expected] of spec.tests.filter(t=>t[0]!=='T16'))report.tests.push({id,input,expected,status:'NOT_VERIFIED',observed:'Não executado: '+error.message});}finally{await context?.close();await browser?.close();}
  report.tests.push(buildCheck(project));report.protectedFilesUnchanged=JSON.stringify(before)===JSON.stringify(protectedSnapshot(project));if(!report.protectedFilesUnchanged)report.warning='Arquivos protegidos mudaram durante a execução. Interrompa e revise o projeto; o checker não desfaz seu código.';
  const failed=report.tests.filter(t=>t.status==='FAIL').length,pending=report.tests.filter(t=>t.status==='NOT_VERIFIED').length;
  report.result=failed||!report.protectedFilesUnchanged?'FAIL':pending?'PARTIAL':'PASS';report.officialGrade=null;
  const out=safeOutput(project),file=path.join(out,'checker-04.json'),tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(report,null,2));fs.renameSync(tmp,file);
  for(const t of report.tests)console.log(`${t.status==='PASS'?'OK':t.status==='FAIL'?'FALHOU':'NÃO VERIFICADO'} ${t.id} — ${t.status==='PASS'?t.input:t.observed.split('\n')[0]}`);
  console.log('\nRelatório: docs/entregas/missao-04/checker-04.json\nResultado técnico: '+report.result+'. A nota depende da avaliação docente.');
  return {exitCode:report.result==='FAIL'?1:report.result==='PARTIAL'?2:0,report};
}
